### PR TITLE
add landing message #1

### LINKED ISSUE #1: Issue

### PR DESCRIPTION
**Pull request by Ptunnage1**

### CODE REVIEW

**Comment by dhuling3** [comment]
I am not convinced with the <h1> code

**Comment by Ptunnage1** [comment]
I will work on that

**Review by dhuling15 — COMMENTED** [review]
I am not satisified with the <h1> code

**Review by dhuling15 — CHANGES_REQUESTED** [review]
I am not convinced about the <h1> code

**Pull request merged**
